
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABA = 8;
  public static final int ARR = 9;
  public static final int LP = 4;
  public static final int TERMINO = 11;
  public static final int RP = 5;
  public static final int DAVALOR = 12;
  public static final int COLOR = 6;
  public static final int IZQ = 13;
  public static final int DER = 10;
  public static final int POS = 14;
  public static final int ID = 18;
  public static final int EDITAR = 15;
  public static final int COMA = 3;
  public static final int EOF = 0;
  public static final int NCOLOR = 16;
  public static final int NUMERO = 17;
  public static final int error = 1;
  public static final int EQ = 2;
  public static final int SALTOLI = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EQ",
  "COMA",
  "LP",
  "RP",
  "COLOR",
  "SALTOLI",
  "ABA",
  "ARR",
  "DER",
  "TERMINO",
  "DAVALOR",
  "IZQ",
  "POS",
  "EDITAR",
  "NCOLOR",
  "NUMERO",
  "ID"
  };
}

